(function (window, document) {
  function getElements() {
    return {
      globalLoader: document.getElementById("globalLoader"),
      form: document.getElementById("transactionForm"),
      descriptionInput: document.getElementById("description"),
      categoryInput: document.getElementById("transactionCategory"),
      amountInput: document.getElementById("amount"),
      amountStepUpBtn: document.getElementById("amountStepUpBtn"),
      amountStepDownBtn: document.getElementById("amountStepDownBtn"),
      dateInput: document.getElementById("transactionDate"),
      dateStepUpBtn: document.getElementById("dateStepUpBtn"),
      dateStepDownBtn: document.getElementById("dateStepDownBtn"),
      formFeedback: document.getElementById("formFeedback"),
      appToast: document.getElementById("appToast"),
      list: document.getElementById("transactionsList"),
      balanceDisplay: document.getElementById("balance"),
      charCount: document.getElementById("charCount"),
      logoutBtn: document.getElementById("logoutBtn"),
      editProfileBtn: document.getElementById("editProfileBtn"),
      introDisplay: document.querySelector(".intro"),
      nameDisplay: document.querySelector(".name"),
      avatarDisplay: document.getElementById("dashboardAvatar"),
      logoutModal: document.getElementById("logoutModal"),
      confirmLogoutBtn: document.getElementById("confirmLogout"),
      cancelLogoutBtn: document.getElementById("cancelLogout"),
      deleteModal: document.getElementById("deleteModal"),
      confirmDeleteBtn: document.getElementById("confirmDelete"),
      cancelDeleteBtn: document.getElementById("cancelDelete"),
      toggleTransactionsBtn: document.getElementById("toggleTransactionsBtn"),
      chartFilterButtons: document.querySelectorAll(".chart-filter-btn"),
      chartPeriod: document.getElementById("chartPeriod"),
      periodResultCard: document.getElementById("periodResultCard"),
      subtractFirstIncomeControl: document.getElementById("subtractFirstIncomeControl"),
      subtractFirstIncomeCheckbox: document.getElementById("subtractFirstIncomeCheckbox"),
      periodResultRange: document.getElementById("periodResultRange"),
      periodResultMessage: document.getElementById("periodResultMessage"),
      analyticsReferenceMonth: document.getElementById("analyticsReferenceMonth"),
      analyticsLoading: document.getElementById("analyticsLoading"),
      analyticsError: document.getElementById("analyticsError"),
      analyticsErrorMessage: document.getElementById("analyticsErrorMessage"),
      analyticsEmpty: document.getElementById("analyticsEmpty"),
      analyticsContent: document.getElementById("analyticsContent"),
      retryAnalyticsBtn: document.getElementById("retryAnalyticsBtn"),
      categoryChartWrapper: document.getElementById("categoryChartWrapper"),
      categoryChartEmpty: document.getElementById("categoryChartEmpty"),
      comparisonCards: document.getElementById("comparisonCards"),
      outlierList: document.getElementById("outlierList"),
      projectionValue: document.getElementById("projectionValue"),
      projectionMethod: document.getElementById("projectionMethod"),
      projectionWarning: document.getElementById("projectionWarning"),
      reportMonth: document.getElementById("reportMonth"),
      reportDownloadButtons: document.querySelectorAll(".report-download-btn"),
      reportFeedback: document.getElementById("reportFeedback"),
      pdfPreviewModal: document.getElementById("pdfPreviewModal"),
      pdfPreviewFrame: document.getElementById("pdfPreviewFrame"),
      closePdfPreviewBtn: document.getElementById("closePdfPreviewBtn"),
      cancelPdfPreviewBtn: document.getElementById("cancelPdfPreviewBtn"),
      downloadPreviewedPdfBtn: document.getElementById("downloadPreviewedPdfBtn")
    };
  }

  window.EZSaldoDashboardDom = {
    getElements
  };
})(window, document);
